In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
%matplotlib inline
from matplotlib.pylab import rcParams
rcParams['figure.figsize'] = 25, 16
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

In [2]:
cur_dir = os.getcwd()

In [3]:
df = pd.read_csv(cur_dir + "//features_phase6a.csv")

In [4]:
df.shape

(17337, 135)

In [11]:
df.LABEL = df.LABEL.astype('category')
df.LABEL = df.LABEL.cat.codes

In [12]:
## X -> features, y -> label
X= df.loc[:,'FG1':'SEP']
y = df.loc[:,'LABEL']

In [13]:
X.shape

(17337, 134)

In [16]:
y.shape

(17337, 17)

In [15]:
from keras.utils import np_utils
y = np_utils.to_categorical(y)

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [19]:
X_train.shape[1:]

(134,)

In [20]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

In [25]:
classifier = Sequential()

In [26]:
classifier.add(Dense(output_dim = 75, init = 'uniform', activation = 'relu', input_dim = 134))
# Adding the second hidden layer
classifier.add(Dense(output_dim = 75, init = 'uniform', activation = 'relu'))
classifier.add(Dropout(0.7))
# Adding the output layer
classifier.add(Dense(units=17, init = 'uniform', activation = 'softmax'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
classifier.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 75)                10125     
_________________________________________________________________
dense_8 (Dense)              (None, 75)                5700      
_________________________________________________________________
dropout_3 (Dropout)          (None, 75)                0         
_________________________________________________________________
dense_9 (Dense)              (None, 17)                1292      
Total params: 17,117
Trainable params: 17,117
Non-trainable params: 0
_________________________________________________________________


C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=134, units=75, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.
C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=75, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=17, activation="softmax", kernel_initializer="uniform")`
  


In [27]:
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 20,
              validation_data=(X_test, y_test))

C:\Users\Dell\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Train on 13869 samples, validate on 3468 samples
Epoch 1/20
13869/13869 [==============================] - 2s - loss: 0.1050 - acc: 0.9653 - val_loss: 0.0753 - val_acc: 0.9745
Epoch 2/20
13869/13869 [==============================] - 2s - loss: 0.0827 - acc: 0.9729 - val_loss: 0.0714 - val_acc: 0.9754
Epoch 3/20
13869/13869 [==============================] - 2s - loss: 0.0784 - acc: 0.9746 - val_loss: 0.0686 - val_acc: 0.9769
Epoch 4/20
13869/13869 [==============================] - 2s - loss: 0.0755 - acc: 0.9752 - val_loss: 0.0665 - val_acc: 0.9782
Epoch 5/20
13869/13869 [==============================] - 2s - loss: 0.0734 - acc: 0.9761 - val_loss: 0.0656 - val_acc: 0.9780
Epoch 6/20
13869/13869 [==============================] - 2s - loss: 0.0711 - acc: 0.9767 - val_loss: 0.0651 - val_acc: 0.9782
Epoch 7/20
13869/13869 [==============================] - 2s - loss: 0.0702 - acc: 0.9768 - val_loss: 0.0658 - val_acc: 0.9783
Epoch 8/20
13869/13869 [==============================] - 2s -

In [28]:
y_pred = classifier.predict(X_test)

In [31]:
y_pred

array([[  8.96223485e-01,   7.30120167e-02,   6.71317046e-09, ...,
          7.98969631e-06,   1.17145470e-13,   1.83266335e-15],
       [  2.63219978e-15,   9.99485850e-01,   0.00000000e+00, ...,
          1.63744990e-11,   6.37783956e-38,   0.00000000e+00],
       [  1.37687931e-02,   7.39297122e-02,   3.12830082e-08, ...,
          8.23284447e-01,   4.68115043e-03,   1.02971114e-06],
       ..., 
       [  2.23034635e-06,   3.98376665e-09,   3.24329969e-38, ...,
          5.02665346e-13,   2.38855880e-24,   0.00000000e+00],
       [  1.00895934e-01,   1.10774189e-02,   8.79815578e-01, ...,
          2.78780553e-05,   3.74397301e-12,   9.73044236e-13],
       [  1.17923171e-10,   1.38061740e-09,   0.00000000e+00, ...,
          1.07204259e-15,   1.75915156e-30,   0.00000000e+00]], dtype=float32)

In [34]:
ab = np.argmax(y_pred,axis=1)

In [39]:
y_test2 = np.argmax(y_test,axis=1)

In [40]:
y_test

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [41]:
y_test2

array([ 0,  1, 14, ...,  9,  2,  5], dtype=int64)